TASK: classification
NUM_GPUS: 1

POINT_INFO:
  PT_FIX_SAMPLING_TRAIN: True
  PT_FIX_SAMPLING_TEST: True
  USE_PT_QUERY_MASK: True
  SAMPLING_TYPE: hybrid_motion
  NUM_POINTS_TO_SAMPLE: 256
  GRID_SIZE: 16

TRAIN:
  ENABLE: False
  DATASET: UCF101
  BATCH_SIZE: 32

DATA:
  PATH_TO_DATA_DIR: "<SET_YOUR_UCF101_PATH>"
  PATH_PREFIX: ""
  REVERSE_INPUT_CHANNEL: True
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: torchvision
  NUM_FRAMES: 8
  SAMPLING_RATE: 4
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]

MODEL:
  NUM_CLASSES: 101
  MODEL_NAME: PACE
  LOSS_FUNC: cross_entropy
  METHOD:
    CLIP_MODEL_NAME: ViT-B/16
    FREEZE_CLIP: True
    TRAJ_INSERT_LAYERS: 6

TEST:
  ENABLE: True
  DATASET: UCF101
  BATCH_SIZE: 64
  CHECKPOINT_FILE_PATH: "<PATH_TO_K400_PRETRAINED_PACE_CHECKPOINT>"

DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True




