TASK: classification
NUM_GPUS: 1

POINT_INFO:
  PT_FIX_SAMPLING_TRAIN: True
  PT_FIX_SAMPLING_TEST: True
  USE_PT_QUERY_MASK: True
  SAMPLING_TYPE: hybrid_motion
  NUM_POINTS_TO_SAMPLE: 256
  GRID_SIZE: 16

TRAIN:
  ENABLE: True
  DATASET: K400
  BATCH_SIZE: 32
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  MIXED_PRECISION: True

DATA:
  PATH_TO_DATA_DIR: "<SET_YOUR_K400_PATH>"
  PATH_PREFIX: ""
  REVERSE_INPUT_CHANNEL: True
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: torchvision
  NUM_FRAMES: 8
  SAMPLING_RATE: 4
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  INV_UNIFORM_SAMPLE: True
  RANDOM_FLIP: False

AUG:
  ENABLE: False

SOLVER:
  BASE_LR: 0.0001
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01]
  STEPS: [0, 20, 40]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.5
  WARMUP_START_LR: 1e-06
  WARMUP_EPOCHS: 5
  OPTIMIZING_METHOD: adamw
  TEMPRATURE: 1.0

MODEL:
  NUM_CLASSES: 400
  MODEL_NAME: PACE
  LOSS_FUNC: cross_entropy
  METHOD:
    CLIP_MODEL_NAME: ViT-B/16
    FREEZE_CLIP: True
    TRAJ_INSERT_LAYERS: 6

TEST:
  ENABLE: True
  DATASET: K400
  BATCH_SIZE: 64

DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True




